<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Smoke Test</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-06-12T17:30:56</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>70c64569-f282-49ef-a430-70123ff49f55</testSuiteGuid>
   <testCaseLink>
      <guid>f023a0d6-5f46-49f6-9650-262cd839cd68</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sponsorship</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aaa39337-4784-461b-961a-0fdde846f051</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7100a1fa-aa94-4e04-8000-60999393970e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e8a9537-5d67-4669-b66e-6d2bd8fa6eab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>631ad956-5077-4e56-88e1-f5e53d8e74ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a33f9008-1845-4d95-8609-a8e07ae4dd40</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>856e1b1d-b8a2-4341-a361-e0e9f797f638</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DonationHiati</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>19bec547-ebdd-438b-a1d4-8245148f162f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91bb1bd1-5f4b-4f0d-8638-40552acb98c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a405ce0-c49d-44e4-830a-d8ffc83fc58c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e21b275-b49b-40b3-b62d-daee3dadf36f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>696ba514-dc7b-4d56-b9c6-6374bc602ca6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DonationGreenApple</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d0486a7e-eded-4979-abb4-fa3f9dbd6e56</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f7955a83-5207-48f6-8b1b-17315922d353</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68fa6faa-b9fc-40df-9a35-351593cb5ea7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ba2662b-4e56-412d-89e3-a7e913782a1d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>12455f28-25a5-47ab-8c34-1e2f8fbf6927</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DonationUsgbc</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>26b29f4d-efda-401e-ad29-9f8ec6241e39</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0658c527-479e-417b-91f2-087a3c86e766</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28bfbc86-e0da-4676-8ab7-499c4f111852</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>26d49b6b-fe09-477e-994f-89b5d34839ef</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8b9afd89-67c4-45f8-94f2-2adb0242ce8e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Store</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f973f16-f806-476d-83c1-dbb97fab90bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f933c13-a910-43cc-99a2-0ee308188848</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>655073de-6587-4960-982a-c1a55390542e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8619bda8-d36c-439b-9e4c-9a2e9cfc9822</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0ea0f4d6-24de-477d-abc0-d16bf40167df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ebff8054-ccbf-4015-acd9-4abdeebdeb1f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>39841191-95c5-4d8b-a09f-602f9840e81e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7ad2189-391a-4430-8a47-fa1125f9c745</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84af1370-f1dc-473e-b9a2-dea3f3f61404</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4ca1b06-0467-47ec-a2fc-9eee4e25c681</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>802d2827-f891-4f91-8840-0c8ca53bbd7e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0bffb940-9f01-4bb0-94ad-253628f0ff55</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Communityregistration</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3cc19fbe-347f-4c80-a098-9549710b955b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2288aca0-30a5-45f1-9d50-c6bb1bb37c57</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c707ef37-a487-4e7e-a690-8cc7ac843f5a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e29d1bdb-f99e-4eed-9c4d-940b0b97f88d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ff97675-f139-4c6e-9cdb-17f7fd82488d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3b9e341a-1e7f-44dc-a900-5620537b2a60</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ExamRegistration</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d82bfa4-0e93-4d50-9724-2bb8af7a1af3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0897efb5-eb10-4591-8f58-57b78c88bd5c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d988fb4-f0f6-47fd-a2d9-92b1da0daad6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af8acf47-8912-4249-8cb9-e36382b318f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f754b60-ad67-4d86-99c1-978d0cf30e34</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>befcdf98-dc06-4772-8e7c-7a74a9535eac</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fab57c5a-d30b-4c64-9310-77aa0c492bc3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Membership</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>27238050-6873-497b-869e-5aeb762e994e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6949c68-2019-40ff-b910-3eed85d7a84e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d62b566f-5358-41de-bbac-3b2677db435a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f99037c6-3091-40df-9285-52af4a4182aa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>256a9025-5c84-440b-bac6-76181ef5a90c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f90b645-fc9c-4865-b719-82afa202bb2b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
