<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_ONE_DAY</name>
   <tag></tag>
   <elementGuidId>e6430b09-9bbe-4ff7-bfbf-91a593b94b05</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>expected-delivery-time</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ONE_DAY</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;usgbc-payment-form&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4 col-xs-12 col-md-push-8&quot;]/div[1]/div[@class=&quot;col-md-12 col-xs-12&quot;]/div[@class=&quot;sidebar sidebar_payment&quot;]/div[1]/table[1]/tbody[1]/tr[4]/td[@class=&quot;expected-delivery-time&quot;]</value>
   </webElementProperties>
</WebElementEntity>
