<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_USGBC Northern Californ</name>
   <tag></tag>
   <elementGuidId>b936c7ea-ae7d-4ec8-83b0-86891243c87c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='edit-community-name']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;edit-community-name&quot;)[count(. | //select[@class = 'col-md-7 col-xs-12 usgbc-form-input form-select' and @autofocus = 'autofocus' and @data-drupal-selector = 'edit-community-name' and @id = 'edit-community-name' and @name = 'community_name' and (text() = 'USGBC Northern CaliforniaUSGBC National Capital RegionUSGBC North CarolinaUSGBC West Virginia' or . = 'USGBC Northern CaliforniaUSGBC National Capital RegionUSGBC North CarolinaUSGBC West Virginia')]) = count(//select[@class = 'col-md-7 col-xs-12 usgbc-form-input form-select' and @autofocus = 'autofocus' and @data-drupal-selector = 'edit-community-name' and @id = 'edit-community-name' and @name = 'community_name' and (text() = 'USGBC Northern CaliforniaUSGBC National Capital RegionUSGBC North CarolinaUSGBC West Virginia' or . = 'USGBC Northern CaliforniaUSGBC National Capital RegionUSGBC North CarolinaUSGBC West Virginia')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-7 col-xs-12 usgbc-form-input form-select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autofocus</name>
      <type>Main</type>
      <value>autofocus</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-selector</name>
      <type>Main</type>
      <value>edit-community-name</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-community-name</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>community_name</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>USGBC Northern CaliforniaUSGBC National Capital RegionUSGBC North CarolinaUSGBC West Virginia</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-community-name&quot;)</value>
   </webElementProperties>
</WebElementEntity>
