<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_expected-delivery-time</name>
   <tag></tag>
   <elementGuidId>4ffb0d48-ced6-47a7-b8d2-8db2720142a8</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>expected-delivery-time</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;usgbc-store-contact-form&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 col-xs-12&quot;]/div[@class=&quot;text-right col-md-4 col-xs-12&quot;]/div[@class=&quot;col-md-12 col-xs-12&quot;]/div[@class=&quot;sidebar&quot;]/table[1]/tbody[1]/tr[4]/td[@class=&quot;expected-delivery-time&quot;]</value>
   </webElementProperties>
</WebElementEntity>
