<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_NC</name>
   <tag></tag>
   <elementGuidId>3ed11f13-318a-422c-9ba2-fdff7f319cb7</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NC</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;usgbc-payment-form&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4 col-xs-12 col-md-push-8&quot;]/div[1]/div[@class=&quot;col-md-12 col-xs-12&quot;]/div[@class=&quot;sidebar sidebar_payment&quot;]/div[1]/div[1]/table[1]/tbody[1]/tr[3]/td[1]</value>
   </webElementProperties>
</WebElementEntity>
